### ISSUE TITLE
Desarrollo de enemigos

### ISSUE THREAD

**Issue by davidcawork** [TecnologiaVideojuegos/proyecto-videojuego-darpa-gamers#2]
En cuanto al desarrollo de los enemigos, sabemos que hereda de la clase Ente por lo que parámetros como:
```java
    private int hp;
    private Punto punto;
    private SpriteSheet sprite;
    private float velocidad;
    int direccion;
```
Son comunes al jugador, habría que añadir mediante un polígono de tipo circle el alcance para empezar el seguimiento del jugador y el daño del enemigo. Al estar esto parametrizado podremos a futuro crear nuevos tipos de enemigo con un sheet de sprites distintos, aunque la clase va a ser común para todos ellos. Que opinas @Unidavid ?

**Comment by Unidavid** [comment]
La idea es bastante buena, pero como aún las clases sprite (para hacer la animación) básicamente aún no están desarrolladas, por lo que en principio nos debemos centrar en realizar la persecución, la idea para ésto es que podemos establecer dos algoritmos en función de su comportamiento. El primero sería tipo pasivo,  mediante un random que se vaya moviendo,  y el hostil para cuando haya detectado a alguien (que se pondrá a perseguirlo), la idea es que al principio actue pasivo y cuando el jugador entra en el rango del enemigo éste cambie a hostil, persiguiéndole hasta que le ataque o básicamente salga de éste rango, que opinas? @davidcawork

**Comment by davidcawork** [comment]
Muy buena idea!  Ve haciendo por aquí update del progreso :smile:

**Comment by Unidavid** [comment]
perfecto me pondré a ello

**Comment by Unidavid** [comment]
del tema de los monstruos ya tenemos los dos movimientos que posee (pasivo y hostil) así como el método encargado de hacer la transición entre ellos (detectar jugador y realizar movimiento) , sólo quedaría hacer que se produzca el intercambio de daño entre jugador y monstruos y viceversa (usando el proyctil que lanzamos), con eso ya tendríamos la gestión de los monstruos en el juego (las colisiones han sido tratadas  exceptuando el pequeño bug de las esquinas que también afecta al jugador).
¿Qué opinas, @davidcawork ?

**Comment by davidcawork** [comment]
En el momento que unifiquemos la resolución del bug de las colisiones por las esquinas ya estaría si :+1: , cuando acabe con inventario y animaciones tratare de ayudarte con ello.

**Comment by Unidavid** [comment]
perfecto, el tema de los monstruos está terminado solo faltaría los bugs, pero ésto ya se puede dar por concluido.
