### ISSUE TITLE
Música y sonidos

### ISSUE THREAD

**Issue by davidcawork** [TecnologiaVideojuegos/proyecto-videojuego-darpa-gamers#4]
Hasta la fecha únicamente habíamos recopilado un sonido de un cofre de la página [https://opengameart.org/](url)  y alguna que otras canciones de uso libre. 

Con el desarrollo de enemigos e inventario vamos a necesitar crear o recopilar algun sonido de uso  libre para:

- Sonido de consumo de una poción(Si hubiera la posibilidad estaría genial encontrar uno para cada tipo de poción)
- Sonido de daño al personaje (El típico ough que hacen los aldeanos de Minecraft)

Te lo asigno @CPCancio

**Comment by CPCancio** [comment]
Okay me pongo a ello

**Comment by CPCancio** [comment]
Ya esta terminado
