### ISSUE TITLE
Bug de las esquinas.

### ISSUE THREAD

**Issue by Unidavid** [TecnologiaVideojuegos/proyecto-videojuego-darpa-gamers#5]
Un problema no reciente es que debido a la separación entre los polígonos del personaje hace que en un caso muy puntual en las esquinas el personaje "atraviese" las paredes provocando que el juego se vuelva menos llamativo.
Para ello he estado pensando en establecer una serie de soluciones que corrijan dicho bug:
1- Reducir lo más posible la distancia de los polígonos. 
2- Implementar un método de detección que se encargue de controlar que el personaje siempre está dentro de los límites jugables del mapa y fuera de los objetos, haciendo que en caso contrario lo lleve al punto de inicio de esa habitación.
¿Qué opináis al respecto?

**Comment by davidcawork** [comment]
Muy buena idea @Unidavid ! En cuanto a la segunda medida lo harás comprobando si el jugador esta dentro o fuera del polígono principal de la escena no?

**Comment by Unidavid** [comment]
SI, la idea es que constantemente se pregunte si los cuatro lados del jugador están dentro de los límites jugables del mapa. Lo estuve implementando pero sucede que la primera vez lo hace bien pero a la segunda ya se raya, estaré echádole un ojo.

**Comment by davidcawork** [comment]
Perfecto :smile:

**Comment by Unidavid** [comment]
Bueno, el bug de las esquinas finalmente se ha controlado, como decía al principio, he implementado un método encargado de detectar que el personaje siempre esté dentro del mapa y fuera de los objetos, en caso contrario, se encargará de moverlo a la posición inicial. Con los monstruos he decidido que cuando llegue a una esquina éste no produzca ningún movimiento hasta que el jugador salga de su rango, de esta manera, se volverá pasivo y podrá salir de esa esquina. Con esto cierro este issue.
