### ISSUE TITLE
Desarrollo de Menús

### ISSUE THREAD

**Issue by davidcawork** [TecnologiaVideojuegos/proyecto-videojuego-darpa-gamers#6]
Desarrollo de menús, y cerramos la parte básica.

@adarve99 ya ha creado la el fondo del menú principal y está en el apartado de gráficos, game_utils. Los botones también te los he subido ahí cualquier botón extra que necesitas dímelo y te lo subo rápido.  

Sería añadir un estado previo al nivel 1, dentro del paradigma del jugo basado en estados. ¿Qué opinas?

**Comment by Unidavid** [comment]
Perfecto, me pondré a ello. Otra cosa, al principio, he pensado meter primero el menú principal, que luego tendrá las opciones, nueva/cargar partida, ranking (se hablará en otra issue) y opciones (a debatir con el resto), entonces nueva partida sería introducir el nombre, la dificultad y ya podrá jugar, mientras que en cargar partida con poner tu nombre ya estaría, que piensas?.

**Comment by davidcawork** [comment]
Me parece una buena idea @Unidavid ! Entonces vamos a ponernos a ello. 

Pd: El ranking en función de la exp, no ?

**Comment by Unidavid** [comment]
Por supuerto, y estoy pensando que no se contabilizará hasta que llegues al nivel último (necesitas pasarte todo el juego básicamente)

**Comment by Unidavid** [comment]
Vale, la gestión de todos los menús ya se ha llevado a cabo, para ello te muestra una especie de diagrama jerárquico donde están todos los menús. Las dobles flechas implican que pueden retornar mientras que las simples solo pueden avanzar.

![IMG_20190515_141355_837](https://user-images.githubusercontent.com/48324034/57775229-d520d880-771c-11e9-8c9a-190bc04315f1.jpg)


Faltaría el caso de mostrar el menú de pausa, pero pienso que eso lo podemos gestionar dentro de cada nivel sin problema.

P.D: La imagen se ve torcida, pero si lo abres en otra pestaña se ve perfectamente (Disculpa las molestias).

**Comment by davidcawork** [comment]
Cerramos pues :smile:
