### ISSUE TITLE
Desarrollo de serialización en menús

### ISSUE THREAD

**Issue by davidcawork** [TecnologiaVideojuegos/proyecto-videojuego-darpa-gamers#7]
Debemos guardar en algún fichero permanente información relativa al estado del inventario, nombre, atributos base, nivel del jugador para que así pueda guardar y salir, y recuperar posteriormente su progreso. 

Esto está bastante relacionado con los estados de menú, lo vamos viendo. Sería aconsejable crear una clase extra para guardar la información a serializar. De esta manera tendríamos acotado en un único objeto lo que queremos guardar y recuperar. ¿Qué te parece @Unidavid ?

**Comment by Unidavid** [comment]
La idea es estupenda, de hecho para poder llevarlo a cabo, habría que hacer  otra clase (aparte de la que se necesita para guardar la información) porque serializar la clase jugador da problemas por el tema de las imágenes y la creación de los objetos tanto inventario como hud, para ello se creará otra clase que se llama info donde contendrá los mismos atributos exceptuando aquellos que lleven imágenes.
¿Qué opinas @davidcawork?

**Comment by davidcawork** [comment]
Fenomenal! 😄

**Comment by Unidavid** [comment]
Perfecto, la serialización en los menús (nueva partida y cargar partida ) funciona perfectamente, faltaría una última cosa que sería el tema de cargar al jugador correctamente en cada nivel, pero ya iremos viendo.

**Comment by davidcawork** [comment]
De momento lo dejamos como está, si nos sobra tiempo miramos eso. :+1:
