### ISSUE TITLE
Desarrollo de la mejora del HUD

### ISSUE THREAD

**Issue by davidcawork** [TecnologiaVideojuegos/proyecto-videojuego-darpa-gamers#8]
Actualmente tenemos el siguiente HUD:

![HUD_actual](https://i.ibb.co/26ZMwtW/1.jpg)

Mostramos la siguiente información al jugador:

- Vida (Corazones parte superior derecha)
- Estados pociones(Fuerza, invulnerabilidad, velocidad en la parte derecha de la pantalla)
- Inventario con las pociones que tiene y de que tipo(Zona central inferior).
- Notificaciones temporales para la adquisición de pociones de cofres, o munición cuando se acaba con algún enemigo(Zona inferior izquierda).

¿Os parece buena idea añadir de forma adicional la munición y la experiencia que lleva en la parte superior derecha? @adarve99 @Unidavid

**Comment by Unidavid** [comment]
Tengo pensado añadir por ejemplo en la esquina inferior derecha un sprite de la munición indicando la cantidad. Pero es una buena idea, además pienso de que es necesario ampliar un poco el tamaño de los slots del inventario, pues parecen un poco pequeños en función del mapa.

**Comment by davidcawork** [comment]
Ya están escalados a 1.5, el problema es que si los escalamos más se van a ver con muy mala calidad :disappointed:

**Comment by Unidavid** [comment]
Vale, entonces no es necesario escalarlo mas. Lo que si, es que es necesario poner como un sprite de una bala (por ejemplo) y al lado ponga x20 que represente la cantidad que tienes.

**Comment by davidcawork** [comment]
Pues ya estaría finalizado por completo 😄 

![Hud acabado](https://i.ibb.co/cwgCSm4/1.jpg)
